FACT-Finder-Web-Components/documentation

- bower.json
- markdown/en/ff-record-list.MD
- src/documentation-app.html
- src/views/contacts-view.html
- src/views/documentation-view.html
add layout + one markdown example file
> Documentation

- README.md
- index.html
* will force a page reload if a new version of the documentation is found
* removed all starter kit specific info from readme
> force sw reload onupdate

- manifest.json
The browser background/address bar now matches the color scheme of the app
> [#16][FIX] theme/background color match ff color

- markdown/en/guides/ready-events.md
- src/data/guides.js
> add Ready Events documenation

- markdown/en/documentation/your-first-search.md
> [#29] fix broken links

- .github/ISSUE_TEMPLATE.md
> [#26] create issue template

- app.js
- markdown/en/core-result-dispatcher.md
- markdown/en/documentation/attribute-basics.md
- markdown/en/documentation/configuration.md
- markdown/en/documentation/ready-events.md
- markdown/en/ff-campaign.md
- markdown/en/ff-compare.md
- markdown/en/ff-header-navigation.md
- markdown/en/ff-navigation.md
- markdown/en/ff-suggest.md
- markdown/en/overview-get-started.md
- src/documentation-app.js
* Fixed more links to use the proper relative markdown link instead of absolute link.
* Some minor code improvements like `const`
> Fix more links

- markdown/en/ff-suggest.md
Fixes #30.
Also added explanation and cross reference why these are necessary.
> [#30] fix triple curly braces issue

- markdown/en/api/ff-checkout-tracking.api.md
- markdown/en/documentation/attribute-basics.md
- markdown/en/ff-checkout-tracking.md
- src/data/api.js
> Add API page for `ff-checkout-tracking`

- src/data/api.js
- src/views/api-view.js
Fixes #39 
Also contains some prettyfication.
> Iss39 browser history

- markdown/en/documentation/attribute-basics.md
- markdown/en/documentation/configuration.md
- markdown/en/documentation/include-scripts.md
- markdown/en/documentation/install-dist.md
- markdown/en/documentation/styling-elements.md
- markdown/en/documentation/your-first-search.md
Some changes that have been made so far.
This PR does **not** resolve issue #33.
Due to lack of time, progress is slow. In order to have at least a few improvements and to prevent accumulation of merge conflicts I created this PR.
> Iss33 proofreading

- src/search/sd-record-list.js
> use relative link

- markdown/en/api/ff-searchbox.api.md
> [#48] parameter is boolean

- markdown/en/api/ff-searchbox.api.md
> [#51] note about URL-encoding

- README.md
- markdown/en/documentation/template-engine.md
- markdown/en/overview-template-engine.md
> [#64, #65] fix links

- markdown/en/ff-header-navigation.md
These are the changes coming with FFWEB-765 (ff-header-navigation support anchor).
> FFWEB-765 ff header nav support anchor

- markdown/en/core-event-aggregator.md
- src/views/api-view.js
> [#72][FIX] use scrollIntoView() instead of anchors

- src/views/api-view.js
> [#87][FIX] scroll to top of page on pageChange

- markdown/en/api/ff-recommendation.api.md
> [#73][FIX] correction, default value

- markdown/en/ff-suggest.md
> [#85][FIX] typo

- markdown/en/ff-asn.md
> [#81] select box native docu

- src/data/api.js
- src/views/api-view.js
> [#100] add "noDemo" flag

- markdown/en/api/ff-searchbox.api.md
> [#98] fix param type

- markdown/en/api/ff-header-navigation.api.md
- markdown/en/core-event-aggregator.md
- markdown/en/core-result-dispatcher.md
- markdown/en/documentation/tracking-guide.md
- markdown/en/ff-asn.md
- markdown/en/ff-searchbox.md
- markdown/en/ff-suggest.md
This PR deals with all of @torsten-knauf 's comments in issue #33.
All files touched while processing these issues were proofread and reformatted.
> [#33] Proofread second edition

- markdown/en/documentation/tracking-with-js.md
> [#110] remove "event" properties from tracking objects

- markdown/en/documentation/tracking-guide.md
Mainly focusing on typos, formatting and grammar.
> A quick proofread of tracking-guide.md

- markdown/1.2/en/core-event-aggregator.md
- markdown/3.0/en/core-event-aggregator.md
> [#130] move important topics to the top

- markdown/1.2/en/api/ff-campaign-shopping-cart.api.md
- markdown/3.0/en/api/ff-campaign-shopping-cart.api.md
> #97 Specify parameter format

- markdown/3.0/en/ff-sortbox.md
Relates to internal ticket FFWEB-938 (PR 320)
> ff-sortbox 3.0 revisited

- markdown/3.0/en/ff-suggest.md
Updated documentation of ```ff-suggest``` to version 3.0.
> FFWEB-968 upgrade ff-suggest documentation

- markdown/3.0/en/api/ff-searchbox.api.md
- markdown/3.0/en/ff-searchbox.md
- markdown/3.0/en/ff-template.md
Upteded documentation of ```ff-searchbox``` and ```ff-searchbutton``` to version 3.0 of these components in all applicable areas.
> FFWEB-958 upgrade ff-searchbox and ff-searchbutton documentation

- src/shared/version-dropdown.js
Meeting about customer support stated, that the  hint about the version must be very obvious. Hence I created a huge ugly box in case someone is reading docu of an old version. I am very open minded about color suggestions ;)
> Multi version support red hint

- markdown/1.2/en/ff-product-teaser-campaign-processor.md
- markdown/1.2/en/ff-record-list-3d.md
- markdown/1.2/en/ff-search-feedback.md
- markdown/1.2/en/ff-suggest-without-input.md
- markdown/3.0/en/ff-product-teaser-campaign-processor.md
- markdown/3.0/en/ff-record-list-3d.md
- markdown/3.0/en/ff-search-feedback.md
- markdown/3.0/en/ff-suggest-without-input.md
- src/data/1.2/api.js
- src/data/3.0/api.js
Related commits are:
- dc365388cba10b6809a7886e3e600a494ef0fba3
- 459dbf0c6b990e871fe3b68dcdac89630fc3e988
- d52c4fd072b23fed50949bb54a82804d7b879ca9
> FFWEB-1030 migrate changes from release/1.2

- app.js
fixes #140 
serve export files using express' static serve
> [#140] use static serve

- markdown/en/documentation/ready-events.md
- markdown/en/ff-asn.md
- markdown/en/ff-campaign.md
- markdown/en/ff-recommendation.md
fixes #106 and some minor ninja improvements
> [#106] Iss106 deferred dispatches

- markdown/1.2/en/documentation/ready-events.md
- markdown/1.2/en/ff-asn.md
- markdown/1.2/en/ff-campaign.md
- markdown/1.2/en/ff-recommendation.md
- markdown/3.0/en/documentation/ready-events.md
- markdown/3.0/en/ff-asn.md
- markdown/3.0/en/ff-campaign.md
- markdown/3.0/en/ff-recommendation.md
cherry-picked release/1.2 commits and applied exact same changes to 3.0 paths
> Iss106 release 3 migration

- markdown/3.0/en/ff-navigation.md
Updated documentation for ff-navigation element.
> Ffweb 962 upgrade ff navigation

- markdown/3.0/en/api/ff-asn.api.md
- markdown/3.0/en/ff-asn.md
Updates `ff-asn` main and api pages.
> FFWEB-941 upgrade ff-asn element

- markdown/1.x/en/api/ff-searchbox.api.md
- markdown/3.x/en/api/ff-searchbox.api.md
Added 'show-asterisk-query' property description.
> FFWEB-972 ff-searchbox hide query

- markdown/3.x/en/ff-sortbox.md
> Ffweb 1134 ff sortbox select

- markdown/1.x/en/ff-campaign.md
- markdown/3.x/en/ff-campaign.md
As requested in FFWEB-1065.
Changes in `v1` and `v3` are identical.
> elaborate on the usage of ff-campaign-feedbacktext

- markdown/1.x/en/api/ff-navigation.api.md
- markdown/3.x/en/api/ff-navigation.api.md
Added some more information to ff-navigation's 'fetch' method description.
> FFWEB-1140 Update fetch method description

- markdown/1.x/en/documentation/template-engine.md
- markdown/3.x/en/documentation/template-engine.md
changes in `1.x` and `3.x` are identically
> Add template hint {{{}}}

- app.js
- config.js
- service-worker.js
- src/actions/app.js
- src/data/1.x/api.js
- src/data/1.x/guides.js
- src/data/3.x/api.js
- src/data/3.x/guides.js
- src/documentation-app.js
- src/my-icons.js
- src/reducers/app.js
- src/search/sd-record-list.js
- src/search/sd-search-box.js
- src/shared-styles.js
- src/util/view-mixin.js
- src/views/api-view.js
- src/views/contacts-view.js
- src/views/documentation-view.js
- src/views/download-view.js
- src/views/home-view.js
- src/views/search-view.js
- src/views/view-404.js
- sw-precache-config.js
> #128 quote consistency

- markdown/3.x/en/api/ff-navigation.api.md
- markdown/3.x/en/ff-navigation.md
Added new properties description ('suggest' and 'navigationData') and a code snippet for usage example.
> Ffweb 1227 navigation new properties

- markdown/3.x/en/documentation/upgrade-guide.md
- src/data/3.x/guides.js
Documentation update according to CSS changes in WebComponents code.
> FFWEB-1254 Update CSS mixins in 3.0 migration guide

- markdown/1.x/en/api/ff-breadcrumb-trail.api.md
- markdown/1.x/en/api/ff-searchbox.api.md
- markdown/3.x/en/api/ff-breadcrumb-trail.api.md
- markdown/3.x/en/api/ff-searchbox.api.md
'show-asterisk-update' property documented for both version of web components (1.x and 3.x)
> FFWEB-1264 ff-breadcrumb-trail: documentation update for a new feature

- markdown/3.x/en/faq.md
Adds questions for _hit-highlighting_ and _clashing polyfills_.
> FAQ updates

- markdown/3.x/en/core-event-aggregator.md
- markdown/3.x/en/core-result-dispatcher.md
- markdown/3.x/en/documentation/configuration.md
- markdown/3.x/en/documentation/routing.md
- markdown/3.x/en/documentation/tracking-with-js.md
- markdown/3.x/en/ff-suggest-without-input.md
- src/search/sd-search-box.js
> Rename occurrences of FFCommunicationEventAggregator

- markdown/3.x/en/documentation/field-roles.md
- markdown/3.x/en/documentation/your-first-search.md
Fixed 2 occurrences of incorrect link in version 3.x.
> FFWEB-1537 Demo link fix in version 3.x

- markdown/1.x/en/ff-record-list.md
- markdown/3.x/en/ff-record-list.md
Added `infinite-scroll` NOTE about using inside recommendation or pushed products
> FFWEB-1512: `infinite-scroll` NOTE

- markdown/1.x/en/ff-campaign.md
- markdown/3.x/en/ff-campaign.md
Added note about `ff-communication` parameters that are required for advisor campaign to work correctly
> FFWEB-1550: Advisor campaigns note

- markdown/1.x/en/ff-compare.md
- markdown/3.x/en/ff-compare.md
Fixes typos, grammar and mustache code listing.
> FFWEB-1591 proofread ff-compare

- markdown/3.x/en/documentation/tracking-guide.md
> FFWEB-1265 add cart tracking hint

- markdown/3.x/en/documentation/single-hit-redirect.md
- src/data/3.x/guides.js
Article refers to not yet released version (working name 3.15.2). It assumes that FFWEB-1719 will be included in that version
> FFWEB-1647: Added guide for manual implementation of single hit redirect

- markdown/3.x/en/documentation/install-dist.md
> Update installation page

- markdown/3.x/en/ff-predictive-basket.md
- src/data/3.x/api.js
- src/views/api-view.js
Adds "Experimental" section to left navigation. It appears only if there are pages registered for it.
Add Predictive Basket page.
> FFWEB-1778 add predictive basket

- config.js
- src/actions/app.js
- src/documentation-app.js
- src/reducers/app.js
- src/search/sd-search-box.js
- src/shared/version-dropdown.js
- src/views/api-view.js
- src/views/home-view.js
Adds status flags for versions to allow more sophisticated version handling.
Also adds `4.x`.
> Version status flags

- markdown/4.x/en/documentation/configuration.md
- markdown/4.x/en/documentation/currency-guide.md
- markdown/4.x/en/documentation/custom-components.md
- markdown/4.x/en/documentation/field-roles.md
- markdown/4.x/en/documentation/include-scripts.md
- markdown/4.x/en/documentation/ready-events.md
- markdown/4.x/en/documentation/routing.md
- markdown/4.x/en/documentation/server-side-rendering.md
- markdown/4.x/en/documentation/tracking-guide.md
- markdown/4.x/en/documentation/tracking-with-js.md
- markdown/4.x/en/documentation/upgrade-guide.md
Just the "documentation" section.
> hint boxes, typo fixes

- markdown/4.x/en/api/ff-communication.api.md
- markdown/4.x/en/documentation/category-pages.md
Adds `market-id`.
Removes Known Issue notice in `category-page`.
> FFWEB-2317 market-id not recognised

- markdown/4.x/en/api/ff-communication.api.md
- markdown/4.x/en/core-result-dispatcher.md
- markdown/4.x/en/documentation/configuration.md
- markdown/4.x/en/documentation/ready-events.md
- markdown/4.x/en/documentation/server-side-rendering.md
- markdown/4.x/en/ff-communication.md
Adds info on `ffCommunicationReady` and cleans up some other parts.
> Add ffCommunicationReady event
