FACT-Finder-Web-Components/documentation

src/views/api-view.js
src/views/documentation-view.js
src/views/download-view.js

1. move script tag outside of markdown-html slot
2. bind path to src attribute, not parameter ($ suffix)
3. use one way data binding

[#62] implement marked-element according to its current documentation

---

src/search/sd-search-box.js

fixes #12 
Previously, clicking on the search-icon when the search-bar was open the blur event would cause the bar to collapse, but the `transitioning` property would still be falsy at the moment the click-handler triggers the `show()` method. 
Ignore blur-event if the `relatedTarget` is the search-icon-button.
Let the button toggle the bar instead.

[#12] prevents double-toggle of search-bar

---

markdown/en/ff-campaign.md

`ff-campaign-redirect` has a new attribute: `relative-to-origin`.
This commit adds the explanation on the behaviour of if.

Explanation of the new attribute (relative-to-origin) on ff-campaign-redirect

---

markdown/en/core-result-dispatcher.md
package.json
src/documentation-app.js

fixes #80 
Typo fixed and class now uses `is()` getter in custom elements definition

[#80] fix typo

---

src/views/api-view.js

fixes #76 
`activeTab` is defaulted to `docs` on initial page change, but becomes empty string when you click the same anchor again. this causes *no* tab to be selected => page looks cleared
solution:
move the default assignment to `activeTab`'s observer.

[#76][FIX] click on same menu item bug

---

markdown/en/api/ff-record-list.api.md
markdown/en/api/ff-searchbox.api.md
markdown/en/documentation/configuration.md
markdown/en/documentation/currency-guide.md
markdown/en/documentation/include-scripts.md
markdown/en/documentation/styling-elements.md
markdown/en/documentation/tracking-guide.md
markdown/en/ff-header-navigation.md
markdown/en/ff-tag-cloud.md
markdown/en/overview-styling-elements.md

I included `search-immediate` because it was already there. What do you think about removing it from the "3. Configuration" section and move it to "4. Your First Search". My reasoning is, that it is useful for first search and things like category pages, but it is to much information for minimal setup. Specially with the note in this section, that you don't always want to use it, it feels missplaced there to me.
If you agree, I would do that in another future ticket / branch.

Ffweb 860 js configuration of ff communication

---

markdown/en/api/ff-middleware.api.md
markdown/en/ff-middleware.md
src/data/api.js

Adds a page for `ff-middleware` and `ff-multi-attribute-parsing`
Doesn't have a demo. I'm wondering whether it would make sense at all to have one in this case.

[FFWEB-805] add pages for ff-middleware and ff-multi-attribute-parsing

---

markdown/1.2/en/api/ff-asn.api.md
markdown/1.2/en/api/ff-breadcrumb-trail.api.md
markdown/1.2/en/api/ff-campaign.api.md
markdown/1.2/en/api/ff-header-navigation.api.md
markdown/1.2/en/api/ff-navigation.api.md
markdown/1.2/en/api/ff-paging-dropdown.api.md
markdown/1.2/en/api/ff-paging.api.md
markdown/1.2/en/api/ff-products-per-page.api.md
markdown/1.2/en/api/ff-record-list.api.md
markdown/1.2/en/api/ff-sortbox.api.md
markdown/1.2/en/api/ff-suggest.api.md
markdown/1.2/en/ff-record-list.MD.bak
markdown/3.0/en/api/ff-asn.api.md
markdown/3.0/en/api/ff-breadcrumb-trail.api.md
markdown/3.0/en/api/ff-campaign.api.md
markdown/3.0/en/api/ff-header-navigation.api.md
markdown/3.0/en/api/ff-navigation.api.md
markdown/3.0/en/api/ff-paging-dropdown.api.md
markdown/3.0/en/api/ff-paging.api.md
markdown/3.0/en/api/ff-products-per-page.api.md
markdown/3.0/en/api/ff-record-list.api.md
markdown/3.0/en/api/ff-sortbox.api.md
markdown/3.0/en/api/ff-suggest.api.md
markdown/3.0/en/ff-record-list.MD.bak
markdown/3.0/en/ff-sortbox.md

Updates the `ff-sortbox` article according to the LitElement migration.
Also contains a brush up of the description of the `dom-updated` event on the `api` pages.

ff-sortbox 3.0 update

---

markdown/3.0/en/api/ff-header-navigation.api.md

Documentation of the latest bugfix in `ff-header-navigation`.
If `ff-header-navigation` gets migrated to LitElement before the `3.0` release, this change is not relevant.

add mixin section to ff-header-navigation for nav-elements' anchors

---

src/data/3.0/api.js
src/views/download-view.js

Usage is low and time to release is not enough for migration to LitElement.
If actual demand is there, we can reintroduce it some time in the future.

Remove ff-carousel from 3.0

---

markdown/3.0/en/documentation/include-scripts.md
markdown/3.0/en/documentation/upgrade-guide.md
markdown/3.0/en/ff-suggest.md
src/data/3.0/guides.js
src/views/download-view.js

I think, it is nice to only have one branch for release/3.0. The upgrade guide is surely not finished yet, but an initial idea of how it might look.
I also added a link to the changelog in the download section, so that the user can easily see the changes, before he downloads a new version.
2 Things I like to discuss shortly (for a future PR):
1. I noticed that the titles in the side navigation bar don't always match the title of the pages (e.g. _Including Scripts_ in the side bar and as page title _Boilerplate_. Is it a good practise to keep those the same?
2. Changing the boilerplate I noticed, that our previous bundle was called _elements.bundle.js_ and now it is called _bundle,js_. Any objections against keeping the old name?

FFWEB-839 & FFWEB-842 upgrading to v3

---

markdown/3.0/en/ff-asn.md

update ff-asn native select-box section to more accurately explain usage

FFWEB-1076 asn native selectbox fix

---

markdown/3.0/en/ff-navigation.md

1. Removed every slot="item" occurrence from HTML samples and additional info about item slots as it is not relevant any more.
2. Added missing slashes to <img> tag in HTML samples (for ff-navigation) as <img /> is a self-closing tag.

FFWEB-962 upgrade ff-navigation

---

markdown/1.x/en/api/ff-middleware.api.md
markdown/1.x/en/ff-middleware.md
markdown/1.x/en/ff-product-teaser-campaign-processor.md
markdown/3.x/en/api/ff-middleware.api.md
markdown/3.x/en/ff-middleware.md
markdown/3.x/en/ff-product-teaser-campaign-processor.md

Previously there was only a dedicated page.
Middleware page is intended to list all available modules therefore this addition.

add ff-product-teaser-campaign-processor to ff-middleware

---

markdown/1.x/en/api/ff-similar-products.api.md
markdown/3.x/en/api/ff-similar-products.api.md

Looked like a copy-and-paste error from `ff-recommendation`

fix description of getSimilarProducts()

---

markdown/1.x/en/core-event-aggregator.md
markdown/3.x/en/core-event-aggregator.md

Some typo and grammar fixes for `1.x` and `3.x`.

fix typos and other errors in EventAggregator

---

config.js

as we have release `1.3.0` update  shown version number in version dropdown to `1.x`

[update-version-dropdown-to-1x"]

---

markdown/1.x/en/api/ff-search-feedback.api.md
markdown/1.x/en/api/ff-tag-cloud.api.md
markdown/1.x/en/core-result-dispatcher.md
markdown/1.x/en/documentation/currency-guide.md
markdown/1.x/en/documentation/ready-events.md
markdown/1.x/en/documentation/template-engine.md
markdown/1.x/en/documentation/tracking-guide.md
markdown/1.x/en/ff-carousel.md
markdown/1.x/en/ff-header-navigation.md
markdown/3.x/en/api/ff-search-feedback.api.md
markdown/3.x/en/api/ff-tag-cloud.api.md
markdown/3.x/en/core-result-dispatcher.md
markdown/3.x/en/documentation/currency-guide.md
markdown/3.x/en/documentation/ready-events.md
markdown/3.x/en/documentation/template-engine.md
markdown/3.x/en/documentation/tracking-guide.md
markdown/3.x/en/ff-carousel.md
src/views/download-view.js

Just a few quick typo fixes. Mostly errors revolving around `'s`.
This PR does not claim to fix all typos.

fix various typos

---

markdown/1.x/en/core-result-dispatcher.md
markdown/3.x/en/api/ff-tag-cloud.api.md
markdown/3.x/en/core-result-dispatcher.md
markdown/3.x/en/ff-tag-cloud.md

Documentation adjusted to migrated `ff-tag-cloud` components. Minor fixes (formatting and typos) done.

FFWEB-1135 Migrate ff tag cloud to lit element

---

markdown/3.x/en/ff-filter-cloud.md
src/data/3.x/api.js

In order to display Filter Cloud demo, it must be deployed to  https://search-web-components.fact-finder.de/, which will be done by @omikron-fp .

FFWEB-1397 Enabled demo tab for `ff-filter-cloud`

---

src/views/api-view.js

_addScrollNavigation is only executed in ConnectedCallback when we are initially landed on the EventAggregator subpage. If not, the scroll listeners won't be attached at all.
This Fix adds _addScrollNavigation execution to page change observer

FFWEB-1428: EventAggregator links 404 

---

markdown/3.x/en/api/ff-searchbox.api.md

`async-facets` had been removed from `ff-communication` so it was removed from documentation as well

FFWEB-1510 Remove `async-facets` parameter

---

markdown/3.x/en/api/ff-asn.api.md
markdown/3.x/en/documentation/upgrade-guide.md

`lazy-load` had been removed from `ff-asn-group` so it was removed from documentation as well

FFWEB-1511 Remove lazy-load parameter

---

markdown/3.x/en/api/ff-asn.api.md

1. `submitOnInput` description updated.
2. Added `disableInputFields` and `submitDelay` properties.

FFWEB-1275 `ff-silder-control` documentation update for `submitOnInput` property

---

markdown/3.x/en/api/ff-record-list.api.md

Add deprecation notice onto `3.x` `stamp-always` attribute.

FFWEB-1609 deprecate stamp-always attribute

---

markdown/3.x/en/core-event-aggregator.md
markdown/3.x/en/core-result-dispatcher.md
markdown/3.x/en/documentation/field-roles.md
markdown/3.x/en/documentation/tracking-with-js.md
markdown/3.x/en/ff-record-list-3d.md

Removed `<link rel="import" href="pathToHtmlImport/elements.build.with_dependencies.html">` from code snippets as they are not supported in FACT-Finder WebComponents 3.x.

FFWEB-1629 Remove obsolete references

---

markdown/3.x/en/documentation/install-dist.md
markdown/3.x/en/faq.md

Unfortunately, we are often becoming tickets from customers who try our library before the Web Components security activation. Service Desk asked therefore for a notice in our documentation.

Add activation notice to documentation

---

markdown/4.x/en/documentation/tracking-with-js.md

Updates deprecated `Tracking12` references with stateless `Tracking` namespace.

FFWEB-1838 replace Tracking12 with stateless Tracking namespace

---

markdown/4.x/en/api/ff-communication.api.md
markdown/4.x/en/documentation/upgrade-guide.md

Updates `4.0.0` migration guide and `ff-communication` API page.

FFWEB-1850 require version and api

---

markdown/4.x/en/documentation/tracking-with-js.md
markdown/4.x/en/documentation/upgrade-guide.md

Adds localisation of price fields to Tracking with JS and the migration guide.

FFWEB-1924 localize get records response
